---

## Create TLS certificate and key (((
- name: Create directory for TLS certificate and key
  file:
    path: /etc/epoptes
    state: directory
    mode: 750

## Default is rsa:1024 (weak): http://www.epoptes.org/installation
- name: Generate TLS certificate and key
  command: openssl req -batch -x509 -nodes -newkey rsa:4096 -days 1826 -keyout /etc/epoptes/server.key -out /etc/epoptes/server.crt
  args:
    creates: /etc/epoptes/server.key
## )))

- name: Write configuration for students
  include: write_config_for_host.yml linuxmuster_net_server_hostmode=student

- name: Write configuration for teachers
  include: write_config_for_host.yml linuxmuster_net_server_hostmode=teacher
