---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Assert that configuration is valid
  assert:
    that:
      - '(epoptes__deploy_modes | length) > 0'
  run_once: True
  delegate_to: 'localhost'

- name: Prepare client
  include: prepare_client.yml
  when: ("prepare_client" in epoptes__deploy_modes)
  tags: [ 'role::epoptes:prepare_client' ]

- name: Create key and X.509 certificate
  include: manage_keys.yml
  become: False
  delegate_to: 'localhost'
  tags: [ 'role::epoptes:keys' ]

- name: Write configuration for teachers
  include: 'write_config_for_host.yml'
  with_dict: '{{ epoptes__rooms }}'
  when: ("teacher" in epoptes__deploy_modes or "postsync" in epoptes__deploy_modes)
  vars:
    epoptes__tpl_hostmode: 'teacher'
  loop_control:
    loop_var: epoptes__tpl_room

- name: Write configuration for students
  include: 'write_config_for_host.yml'
  with_dict: '{{ epoptes__rooms }}'
  when: ("student" in epoptes__deploy_modes or "postsync" in epoptes__deploy_modes)
  vars:
    epoptes__tpl_hostmode: 'student'
  loop_control:
    loop_var: epoptes__tpl_room

- name: Write postsync configuration
  template:
    src: 'var/linbo/postsync.sh.j2'
    dest: '{{ epoptes__postsync_script }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: ("postsync" in epoptes__deploy_modes)
