---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Set epoptes__tpl_root_path for postsync mode
  set_fact:
    epoptes__tpl_root_path: '/var/linbo/linuxmuster-client/{{ epoptes__postsync_image_name }}/{{ epoptes__tpl_room.key }}_{{ epoptes__tpl_hostmode }}'
  when: ("postsync" in epoptes__deploy_modes)

# Create directories [[[
- name: Create directory
  file:
    path: '{{ epoptes__tpl_root_path|d("") + "/" + item.file }}'
    state: 'directory'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: epoptes__tpl_hostmode == item.when|d(epoptes__tpl_hostmode)
  with_items:
    - file: 'etc/epoptes'
    - file: 'etc/default'
    - file: 'etc/init.d'
    - file: 'etc/xdg/autostart'
    - file: 'usr/local/share/applications'
      when: 'teacher'
    - file: 'etc/sudoers.d'
      when: 'teacher'
    - file: 'usr/local/bin'
# ]]]

# Handle authentication via public-private-key [[[

- name: Copy the certificate to the student system when deploying on client
  copy:
    src: '{{ epoptes__secret_path + "/" + item.file }}'
    dest: '{{ epoptes__tpl_root_path|d("") + "/etc/epoptes/" + item.file }}'
  when: (epoptes__tpl_hostmode == item.when|d(epoptes__tpl_hostmode) and "postsync" not in epoptes__deploy_modes)
  with_items:
    - file: 'server.key'
      when: 'teacher'
    - file: 'server.crt'

- name: Create symbolic links to the key
  file:
    src: '{{ epoptes__client_key_dir + "/" + item }}'
    path: '{{ epoptes__tpl_root_path|d("") + "/etc/epoptes/" + item }}'
    state: 'link'
    force: True
  when: (epoptes__tpl_hostmode == 'teacher' and "postsync" not in epoptes__deploy_modes)
  with_items:
    - 'server.key'
    - 'server.crt'

# ]]]

# Write configuration files for Epoptes [[[

- name: Write configuration files for Epoptes
  template:
    src: '{{ item.file }}.j2'
    dest: '{{ epoptes__tpl_root_path|d("") }}/{{ item.file }}'
    mode: '{{ item.mode | d("0640") }}'
    ## It is required to allow read permissions for others so that rsync can read the files on the server.
    validate: '{{ item.validate | d(omit) }}'
    owner: 'root'
    group: 'root'
  when: epoptes__tpl_hostmode == item.when|d(epoptes__tpl_hostmode)
  with_items:
    - file: 'etc/default/epoptes'
      when: 'teacher'
      mode: '0644'
    - file: 'etc/default/epoptes-client'
      when: 'student'
      mode: '0644'
    - file: 'etc/xdg/autostart/epoptes-client.desktop'
      mode: '0644'
      when: 'student'
    - file: 'etc/xdg/autostart/epoptes-copy-key.desktop'
      mode: '0644'
      when: 'teacher'
    - file: 'usr/local/bin/epoptes-copy-key.sh'
      mode: '0755'
      when: 'teacher'
    - file: 'usr/local/bin/epoptes-client-loop.sh'
      mode: '0755'
      when: 'student'
    - file: 'etc/sudoers.d/ansible-teacher-epoptes-restart'
      mode: '0644'
      validate: 'visudo -cf %s'
      when: 'teacher'
    # - file: 'usr/share/applications/epoptes.desktop'
    - file: 'usr/local/share/applications/epoptes.desktop'
      mode: '0644'
      when: 'teacher'
    - file: 'etc/init.d/epoptes'
      mode: '0755'
      when: 'teacher'
    - file: 'etc/init.d/epoptes-client'
      mode: '0755'
      when: 'student'

# ]]]

# WIP. Does nothing useful so far. [[[
- name: Enforce epoptes-client running
  template:
    src: '{{ item.file + ".j2" }}'
    dest: '{{ epoptes__tpl_root_path|d("") + "/" + item.file }}'
    mode: '{{ item.mode | d("0640") }}'
    ## It is required to allow read permissions for others so that rsync can read the files on the server.
    validate: '{{ item.validate | d(omit) }}'
    owner: 'root'
    group: 'root'
  when: epoptes__tpl_hostmode == item.when|d(epoptes__tpl_hostmode) and epoptes__enforce|bool
  with_items:
    - file: 'etc/sudoers.d/ansible-wm-restart'
      mode: '0644'
      validate: 'visudo -cf %s'
# ]]]
