---

- name: Set variable
  set_fact:
    linuxmuster_net_server_postsync_dir: "/var/linbo/linuxmuster-client/{{ linuxmuster_net_server_epoptes_via_postsync_image_name }}/{{ linuxmuster_net_server_epoptes_room }}_{{ linuxmuster_net_server_hostmode }}"
  when: linuxmuster_net_server_epoptes_deploy_on_client is not defined or not linuxmuster_net_server_epoptes_deploy_on_client

- name: Set variable
  set_fact:
    linuxmuster_net_server_postsync_dir: ""
  when: linuxmuster_net_server_epoptes_deploy_on_client is string

## Create directories in postsync (((
- name: Create directory postsync
  file:
    path: "{{ linuxmuster_net_server_postsync_dir }}/{{ item.file }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: ((item.when is defined and linuxmuster_net_server_hostmode == item.when) or item.when is not defined)
  with_items:
    - file: "etc/epoptes"
    - file: "etc/default"
    - file: "etc/init.d"
    - file: "etc/xdg/autostart"
    - file: "usr/local/share/applications"
      when: "teacher"
    - file: "etc/sudoers.d"
      when: "teacher"
    - file: "usr/local/bin"
      when: "teacher"
## )))

## Copy TLS certificate and key (only the link) into postsync (((
- name: Copy the certificate into postsync directory
  command: cp "/{{ item }}" "{{ linuxmuster_net_server_postsync_dir }}/{{ item }}"
  args:
    creates: "{{ linuxmuster_net_server_postsync_dir }}/{{ item }}"
  when: (
         (
          linuxmuster_net_server_epoptes_deploy_on_client is not defined or
          not linuxmuster_net_server_epoptes_deploy_on_client
         )
         and linuxmuster_net_server_hostmode == 'student'
        )
  with_items:
    - "etc/epoptes/server.crt"

- name: Create symbolic links to the key
  file:
    src: '{{ linuxmuster_net_server_epoptes_client_key_dir }}/{{ item }}'
    path: '{{ linuxmuster_net_server_postsync_dir}}/etc/epoptes/{{ item }}'
    state: link
    force: yes
  when: linuxmuster_net_server_hostmode == 'teacher'
  with_items:
    - 'server.key'
    - 'server.crt'

## )))

- name: Write configuration files for epoptes
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ linuxmuster_net_server_postsync_dir }}/{{ item.file }}"
    mode: "{{ item.mode | default('0640') }}"
    validate: '{{ item.validate | default(omit) }}'
    owner: root
    group: root
  when: ((item.when is defined and linuxmuster_net_server_hostmode == item.when) or item.when is not defined)
  with_items:
    - file: "etc/default/epoptes"
      when: "teacher"
      mode: '0644'
    - file: "etc/default/epoptes-client"
      when: "student"
      mode: '0644'
    - file: "etc/xdg/autostart/epoptes-client.desktop"
      mode: "0644"
      when: "student"
    - file: "etc/xdg/autostart/copy-key.sh"
      mode: "0644"
      when: "teacher"
    - file: "usr/local/bin/epoptes-copy-key.sh"
      mode: "0755"
      when: "teacher"
    - file: "etc/sudoers.d/ansible-teacher-epoptes-restart"
      mode: "0640"
      validate: 'visudo -cf %s'
      when: "teacher"
    # - file: "usr/share/applications/epoptes.desktop"
    - file: "usr/local/share/applications/epoptes.desktop"
      mode: "0644"
      when: "teacher"
    - file: "etc/init.d/epoptes"
      mode: "0755"
      when: "teacher"
    - file: "etc/init.d/epoptes-client"
      mode: "0755"
      when: "student"
