---

- name: Setup and manage Epoptes
  hosts: [ 'ypid_service_epoptes' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.epoptes
      tags: [ 'role::epoptes' ]
